// Cross-platform preinstall hook (Node.js CommonJS).
// Replaces the original Bash `sh -c '...'` hook so `pnpm install` works on
// Windows (PowerShell / CMD) as well as Linux / macOS.
//
// Responsibilities:
//   1. Remove any stray package-lock.json / yarn.lock files that might have
//      been accidentally committed or generated by running npm / yarn.
//      These lockfiles conflict with pnpm-lock.yaml.
//   2. Refuse to run unless the package manager actually running the
//      install is pnpm. Protects the workspace from partial installs via
//      npm / yarn that would ignore pnpm-workspace.yaml, workspace
//      catalog, minimum-release-age, and native-binary overrides — all
//      security- and correctness-critical configuration.

const fs = require("node:fs");
const path = require("node:path");

const projectRoot = path.resolve(__dirname, "..");

// 1. Cleanup conflicting lockfiles (best-effort, ENOENT is fine)
const CONFLICTING_LOCKFILES = ["package-lock.json", "yarn.lock"];
for (const f of CONFLICTING_LOCKFILES) {
  const p = path.join(projectRoot, f);
  try {
    fs.unlinkSync(p);
  } catch {
    /* file did not exist or was unlinkable — ignore */
  }
}

// 2. Package-manager check. pnpm sets `npm_config_user_agent` to a value
//    that starts with "pnpm/" (e.g. "pnpm/10.26.1 npm/? node/v20.18.0 win32 x64").
const ua = process.env.npm_config_user_agent ?? "";
if (!ua.startsWith("pnpm/")) {
  process.stderr.write("Use pnpm instead\n");
  process.exit(1);
}
