const DOMAIN = process.env.EXPO_PUBLIC_DOMAIN ?? "";
const BANNER_BASE = DOMAIN ? `https://${DOMAIN}` : "";

const TEAM_BANNER_FILES: Record<string, string> = {
  "FC Porto": "porto.jpg", "Porto": "porto.jpg",
  "Benfica": "benfica.jpg", "SL Benfica": "benfica.jpg",
  "Sporting CP": "sporting.jpg", "Sporting": "sporting.jpg",
  "Braga": "braga.jpg", "SC Braga": "braga.jpg",
  "Famalicão": "famalicao.jpg", "Famalicao": "famalicao.jpg", "FC Famalicão": "famalicao.jpg",
  "Gil Vicente": "gil-vicente.jpg",
  "Moreirense": "moreirense.jpg",
  "Vitória SC": "vitoria-sc.jpg", "Vitoria SC": "vitoria-sc.jpg",
  "Vitória de Guimarães": "vitoria-sc.jpg", "V. Guimaraes": "vitoria-sc.jpg",
  "Estoril Praia": "estoril.jpg", "Estoril": "estoril.jpg",
  "Alverca": "alverca.jpg", "FC Alverca": "alverca.jpg",
  "Inter": "inter.jpg", "Inter Milan": "inter.jpg", "Internazionale": "inter.jpg",
  "Milan": "milan.jpg", "AC Milan": "milan.jpg",
  "Juventus": "juventus.jpg",
  "Napoli": "napoli.jpg",
  "Roma": "roma.jpg", "AS Roma": "roma.jpg",
  "Lazio": "lazio.jpg", "SS Lazio": "lazio.jpg",
  "Atalanta": "atalanta.jpg",
  "Fiorentina": "fiorentina.jpg",
  "Bologna": "bologna.jpg",
  "Torino": "torino.jpg",
  "Como": "como.jpg", "Como 1907": "como.jpg",
  "Parma": "parma.jpg", "Parma Calcio": "parma.jpg",
  "Besiktas": "besiktas.jpg", "Beşiktaş": "besiktas.jpg",
  "Fenerbahce": "fenerbahce.jpg", "Fenerbahçe": "fenerbahce.jpg",
  "Galatasaray": "galatasaray.jpg",
  "Goztepe": "goztepe.jpg",
  "Kocaelispor": "kocaelispor.jpg",
  "Konyaspor": "konyaspor.jpg",
  "Rizespor": "rizespor.jpg",
  "Samsunspor": "samsunspor.jpg",
  "Trabzonspor": "trabzonspor.jpg",
  "Istanbul Basaksehir": "basaksehir.jpg", "Basaksehir": "basaksehir.jpg",
  "Ipswich": "ipswich.jpg", "Ipswich Town": "ipswich.jpg",
  "Hull City": "hull.jpg", "Hull": "hull.jpg",
  "Derby County": "derby.jpg", "Derby": "derby.jpg",
  "Middlesbrough": "middlesbrough.jpg",
  "Coventry City": "coventry.jpg", "Coventry": "coventry.jpg",
  "Birmingham City": "birmingham.jpg", "Birmingham": "birmingham.jpg",
  "Leicester City": "leicester.jpg", "Leicester": "leicester.jpg",
  "Sheffield United": "sheffield-utd.jpg", "Sheffield Utd": "sheffield-utd.jpg",
  "Southampton": "southampton.jpg",
  "Wrexham": "wrexham.jpg",
  "Atlanta United": "atlanta-united.jpg",
  "Austin FC": "austin-fc.jpg",
  "Columbus Crew": "columbus-crew.jpg",
  "FC Cincinnati": "fc-cincinnati.jpg",
  "Inter Miami": "inter-miami.jpg",
  "LAFC": "lafc.jpg", "LA FC": "lafc.jpg",
  "LA Galaxy": "la-galaxy.jpg",
  "NYCFC": "nycfc.jpg", "New York City FC": "nycfc.jpg",
  "Portland Timbers": "portland-timbers.jpg",
  "Seattle Sounders": "seattle-sounders.jpg", "Seattle Sounders FC": "seattle-sounders.jpg",
};

export function getTeamBannerUrl(teamName: string): string | null {
  if (!BANNER_BASE) return null;
  const file = TEAM_BANNER_FILES[teamName];
  return file ? `${BANNER_BASE}/banners/${file}` : null;
}
